### ISSUE TITLE
support for in floor temperature sensors ?

### ISSUE THREAD

**Issue by davecramer** [HestiaPi/hestia-touch-openhab#15]
Is it possible to support floor sensors easily ?

**Comment by gulliverrr** [comment]
Please describe in full the functionality you expect :)

**Comment by davecramer** [comment]
I'll move to the forum then but I have a hydronic in floor heating system and it has both air and slab (concrete) sensors. For the most part I want to control the slab temperature but also want to monitor the air temp

**Comment by gulliverrr** [comment]
[Moved](https://community.hestiapi.com/t/looking-for-the-ability-to-add-a-slab-sensor/1376).
