### ISSUE TITLE
etc/openhab2/rules missing on ONE branch

### ISSUE THREAD

**Issue by rkoshak** [HestiaPi/hestia-touch-openhab#21]
It looks like the rules are missing on the default branch. I'm sure it's just an oversight.

**Comment by gulliverrr** [comment]
`/home/pi/scripts/openhabloader.sh` fools OH during boot by moving the rules file at boot and once the CPU load goes low it then moves it back to the rules location. If no rules file is found, the default is loaded from the scripts directory.
https://github.com/HestiaPi/hestia-touch-openhab/blob/ONE/home/pi/scripts/openhabloader.sh
