### ISSUE TITLE
String item value shown as text next to selection

### ISSUE THREAD

**Issue by gulliverrr** [HestiaPi/hestia-touch-openhab#41]
Basic UI shows ON/OFF/Boost item value as text next to selection buttons:
![image](https://user-images.githubusercontent.com/5602697/79598219-3949da80-80ec-11ea-9cae-bc077cdc4955.png)
I find it redundant as selected button shows status.
Removing `[%s]` from Paper UI>Configuration>Items did not affect Basic UI.
This was caused after #38 @rkoshak

**Comment by rkoshak** [comment]
That's an easy fix. But removing the `[%s]` isn't enough. This is a long running bug. But you can suppress it using `[]` instead, though I ended up fixing it in the sitemap. Where do you perfer I apply the fix? The sitemap or on the Item?

**Comment by gulliverrr** [comment]
I assume the Item is where it should originate correctly although I understand it is a presentation issue only.
This is happening for all selection items too (Temperature Unit,  System Type and 2nd Stage Heating)

**Comment by rkoshak** [comment]
After looking at it, I think I want to make the fix on the sitemap instead of on the Item itself. If I make the change to the Item, it breaks the Control tab of PaperUI so you no longer see the state of the mode there.

**Comment by gulliverrr** [comment]
Fixed by #43

**Comment by gulliverrr** [comment]
Fixed by #43
