### ISSUE TITLE
On a reboot, the LCD does not always have the current temp set

### ISSUE THREAD

**Issue by rkoshak** [HestiaPi/hestia-touch-openhab#45]
I just noticed on a reboot of the machine, when OH comes back online, the current temperature reading does not always update to the current temp and remains 0. I'm not sure if this is a new problem introduced by the change to fix the setpoint bouncing problem or a problem I'm just noticing.

It is just the LCD though. The Item in openHAB is correctly updated.

**Comment by gulliverrr** [comment]
Fixed by #50
