### ISSUE TITLE
IP info displays error when no wi-fi

### ISSUE THREAD

**Issue by jaythomas** [HestiaPi/hestia-touch-openhab#53]
Expected:
When there is no wi-fi, display nothing (empty string)

Actual results:
A curl error is displayed, pushing the rest of the system info off the LCD screen
![20200530_162014](https://user-images.githubusercontent.com/2344456/83582166-bdc2b200-a50e-11ea-892a-2c44fbae4132.jpg)

**Comment by gulliverrr** [comment]
I believe this is sorted by [this](https://github.com/HestiaPi/hestia-touch-openhab/commit/69d1428b4b38c4cc750c6ffee366ea6cde55dcb9#diff-4e46f298b1efea409f906671bd5067bc) commit. Could you please check the contents of your `home/pi/scripts/getpublicip.sh` if it has this extra `while` check on the top? This will be merged on the next image to be released [1.2](https://github.com/HestiaPi/hestia-touch-openhab/milestone/1).

**Comment by jaythomas** [comment]
I believe this does the trick, but if not I will re-open if I see the issue again. Thanks.
