### ISSUE TITLE
Comfort Range set back to 3 on reboot

### ISSUE THREAD

**Issue by raycekar** [HestiaPi/hestia-touch-openhab#63]
Running v1.2-Dev and I found after a reboot that when set to eco mode, the comfort Range is not persistent.  I usually like mine at 4 degrees :)

**Comment by gulliverrr** [comment]
Hmmm... will look into that. The Comfort_Value Item (under Settings labelled "Comfort Range") needs to be stored in persistent storage.

**Comment by gulliverrr** [comment]
Duplicate of #62
