### ISSUE TITLE
updateone.sh reverts OpenHAB to 2.5.3

### ISSUE THREAD

**Issue by anon8675309** [HestiaPi/hestia-touch-openhab#69]
The `rsync` command [in updateone.sh](https://github.com/HestiaPi/hestia-touch-openhab/blob/ONE/home/pi/scripts/updateone.sh#L23) causes openhab to (partially) get reverted from the version that was installed (e.g. 2.5.12) to 2.5.3.

Steps to reproduce:

1. Set up a pi running a stock jessie image
2. Install openhab2 using the [official instructions](https://v2.openhab.org/download/)
3. Run `openhab-cli info` to see that you have 2.5.12 installed
4. Run updateone.sh
5. Run `openhab-cli info` to see that it now reports that you have 2.5.3 installed

**Comment by anon8675309** [comment]
It appears to be something in `./var/lib/openhab2` that is causing this.  I see that version number hard-coded in a number of places in there.

All of the following files are in `./var/lib/openhab2` and contain 2.5.3:

- config/org/apache/karaf/features.config
- config/profile.config
- config/org_apache_felix_cm_impl_DynamicBindings.config
- etc/branding.properties
- etc/org.apache.karaf.features.cfg
- etc/profile.cfg
- etc/version.properties
- etc/branding-ssh.properties

**Comment by anon8675309** [comment]
It appears that the `openhab-cli info` command gets version information from `/var/lib/openhab2/etc/version.properties`.

**Comment by gkoumanos** [comment]
The mentioned script is only to pull to a local installation the version which is on github only if the reported version installed is lower than the version on the github repo. Right now there is no newer version on github.
All the logic above is inside HestiaPi and the script you mention is not to be called "by hand" but by this "Thing":
https://github.com/HestiaPi/hestia-touch-openhab/blob/efc69c44a1894183c9e6140254faf0b513820ebf/var/lib/openhab2/jsondb/org.eclipse.smarthome.core.thing.Thing.json#L1989

**Comment by gulliverrr** [comment]
The mentioned script is only to pull to a local installation the version which is on github only if the reported version installed is lower than the version on the github repo. Right now there is no newer version on github.
All the logic above is inside HestiaPi and the script you mention is not to be called "by hand" but by this "Thing":
https://github.com/HestiaPi/hestia-touch-openhab/blob/efc69c44a1894183c9e6140254faf0b513820ebf/var/lib/openhab2/jsondb/org.eclipse.smarthome.core.thing.Thing.json#L1989
