### ISSUE TITLE
Wiki update - Remote temperature sensing

### ISSUE THREAD

**Issue by hestiahacker** [HestiaPi/hestia-touch-openhab#75]
I don't have permission to edit the wiki, nor can I clone the wiki and submit a merge request. So I'm going to attach the markdown files here so someone with wiki write access can get them in there.

[_Sidebar.md](https://github.com/HestiaPi/hestia-touch-openhab/files/12482331/_Sidebar.md)
[Ruuvi-temperature-sensors.md](https://github.com/HestiaPi/hestia-touch-openhab/files/12482332/Ruuvi-temperature-sensors.md)
[Remote-temperature-sensors.md](https://github.com/HestiaPi/hestia-touch-openhab/files/12482334/Remote-temperature-sensors.md)

**Comment by gulliverrr** [comment]
Merged. Thank you and apologies for the delay @hestiahacker
