### ISSUE TITLE
Support "Portrait" mode ui

### ISSUE THREAD

**Issue by blazini36** [HestiaPi/hestia-touch-openhab#77]
I have a slightly different hardware setup than the retail HestiaPi using the same screen. This setup requires the screen run upright or "portrait" orientation. 

The home directory of the HestiaPi contains LCD scripts from the OEM, one of them makes it pretty easy to reorient the LCD itself. The main page of the UI doesn't take well to being rotated, the rest of the UI like the pop-ups and info screen appear fine.

I've tried modifying the UI but it's shooting blind unless you have some experience with that environment. I'm sure given the option some people may prefer the portrait style UI on the retail HestiaPi as well.

**Comment by gulliverrr** [comment]
Please use the [UI repo](https://github.com/HestiaPi/hestia-touch-one-ui) for UI issues...
